server:
  port: 8087
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: False
    fetch-registry: False
    service-url:
      default-url: http://{eureka.instance.hostname}:${server.port}/eureka
  